### ISSUE TITLE
Problems with rendering of diagram-js example in React application. Failed to execute 'insertBefore' on 'Node': The new child element contains the parent.

### ISSUE THREAD

**Issue by sok82** [bpmn-io/diagram-js#570]
__Problem description__

Hi guys, 
I'm inspired by your work on diagram-js and want to implement custom diagram editor based on diagram-js in my React application.

Because I didn't found any step-by-step docs i followed an example from [here](https://github.com/bpmn-io/diagram-js-examples) and besides I saw some diagram I have 2 problems on which I'm stuck

1. Palette is not shown at all - for some reasons divs containing palette tools have zero height 
2. After several successful tries moving the shapes browser crashed with exception
`unhandled error in event listener DOMException: Failed to execute 'insertBefore' on 'Node': The new child element contains the parent.
    at prependTo (http://localhost:3000/static/js/6.chunk.js:3138:14)
    at http://localhost:3000/static/js/6.chunk.js:3065:7
    at forEach (http://localhost:3000/static/js/6.chunk.js:14585:16)
    at http://localhost:3000/static/js/6.chunk.js:3063:61
    at forEach (http://localhost:3000/static/js/6.chunk.js:14585:16)
    at GraphicsFactory.push../node_modules/diagram-js/lib/core/GraphicsFactory.js.GraphicsFactory.updateContainments (http://localhost:3000/static/js/6.chunk.js:3054:59)
    at http://localhost:3000/static/js/6.chunk.js:3533:21
    at invokeFunction (http://localhost:3000/static/js/6.chunk.js:2910:13)
    at EventBus.push../node_modules/diagram-js/lib/core/EventBus.js.EventBus._invokeListener (http://localhost:3000/static/js/6.chunk.js:2771:19)
    at EventBus.push../node_modules/diagram-js/lib/core/EventBus.js.EventBus._invokeListeners (http://localhost:3000/static/js/6.chunk.js:2755:24)`

__Steps to Reproduce__

1. I included DiagramEditor from example into react component ReactDiagramEditor (see code below)
```javascript

import { useEffect } from 'react';
import { makeStyles } from '@material-ui/core';
import Editor from "./Editor";

const useStyles = makeStyles(theme => ({
    diagram: {
      '& .palette-icon-lasso-tool' : {
        background: 'url("data:image/svg+xml,%3Csvg%0A%20%20%20%20%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20%0A%20%20%20%20%20fill%3D%22none%22%0A%20%20%20%20%20stroke%3D%22%23000%22%0A%20%20%20%20%20stroke-width%3D%221.5%22%0A%20%20%20%20%20width%3D%2246%22%0A%20%20%20%20%20height%3D%2246%22%3E%0A%20%20%3Crect%20x%3D%2210%22%20y%3D%2210%22%20width%3D%2216%22%20height%3D%2216%22%20stroke-dasharray%3D%225%2C%205%22%20%2F%3E%0A%20%20%3Cline%20x1%3D%2216%22%20y1%3D%2226%22%20x2%3D%2236%22%20y2%3D%2226%22%20stroke%3D%22black%22%20%2F%3E%0A%20%20%3Cline%20x1%3D%2226%22%20y1%3D%2216%22%20x2%3D%2226%22%20y2%3D%2236%22%20stroke%3D%22black%22%20%2F%3E%0A%3C%2Fsvg%3E")'
      },    
      '& .palette-icon-create-shape' : {
        background: 'url("data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20fill%3D%22none%22%20stroke%3D%22%23000%22%20stroke-width%3D%221.5%22%20width%3D%2246%22%20height%3D%2246%22%3E%3Crect%20x%3D%2210%22%20y%3D%2213%22%20width%3D%2226%22%20height%3D%2220%22%2F%3E%3C%2Fsvg%3E")'
      },    
      '& .palette-icon-create-frame' : {
        background: 'url("data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20fill%3D%22none%22%20stroke%3D%22%23000%22%20stroke-width%3D%221.5%22%20stroke-dasharray%3D%224%22%20width%3D%2246%22%20height%3D%2246%22%3E%3Crect%20x%3D%2210%22%20y%3D%2213%22%20width%3D%2226%22%20height%3D%2220%22%2F%3E%3C%2Fsvg%3E")'
      },    
      '& .context-pad-icon-remove' : {
        background: 'url("data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20fill%3D%22none%22%20stroke%3D%22%23000%22%20stroke-width%3D%221.5%22%20width%3D%2246%22%20height%3D%2246%22%3E%3Cline%20x1%3D%225%22%20y1%3D%225%22%20x2%3D%2215%22%20y2%3D%2215%22%2F%3E%3Cline%20x1%3D%2215%22%20y1%3D%225%22%20x2%3D%225%22%20y2%3D%2215%22%2F%3E%3C%2Fsvg%3E") !important'
      },    
      '& .context-pad-icon-connect' : {
        background: 'url("data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20fill%3D%22none%22%20stroke%3D%22%23000%22%20stroke-width%3D%221.5%22%20width%3D%2246%22%20height%3D%2246%22%3E%3Cline%20x1%3D%2215%22%20y1%3D%225%22%20x2%3D%225%22%20y2%3D%2215%22%2F%3E%3C%2Fsvg%3E") !important'
      }    
    }
  }));
  
function ReactDiagramEditor() {

    const classes = useStyles();

    useEffect(
        () => {
            const diagramContainer = document.getElementById('diagramContainer');
            if (diagramContainer) {
                const diagram = new Editor({
                                          container: diagramContainer
                                    });
                
                const canvas = diagram.get('canvas');
                const elementFactory = diagram.get('elementFactory');
                
                // add root
                var root = elementFactory.createRoot();
                
                canvas.setRootElement(root);

                // add shapes
                var shape1 = elementFactory.createShape({
                    x: 150,
                    y: 100,
                    width: 100,
                    height: 80
                });
                
                canvas.addShape(shape1, root);
                
                var shape2 = elementFactory.createShape({
                    x: 290,
                    y: 220,
                    width: 100,
                    height: 80
                });
                
                canvas.addShape(shape2, root);
                
                
                var connection1 = elementFactory.createConnection({
                    waypoints: [
                    { x: 250, y: 180 },
                    { x: 290, y: 220 }
                    ],
                    source: shape1,
                    target: shape2
                });
                
                canvas.addConnection(connection1, root);
                
            }
        },[])

    return <div id="diagramContainer" className={classes.diagram} style={{height:'100%'}}></div>
}

export default ReactDiagramEditor;
```
2. And just place it on an empty page
3. When page renders I see a diagram
      3a. With no palette
      3b. With error after moving one of the shapes several times

__Expected Behavior__
1. Palette is shown
2. No error in console

__Environment__

 - Browser: [Chrome]
 - OS: [MacOs]
 - Library version: [7.4.0]

**Comment by sok82** [comment]
At last I've managed to fix it.
Sorry for troubling you guys - it was simple.
'diagram-js.css" file was not linked properly.

After I added file in a component with a simple
```
import 'diagram-js/assets/diagram-js.css';
```
all problems listed above disappeared
